#pragma once
void test_bool();
void backoutput();
void convert();
void comp_char();
void comp_str();
void cmp_while();
void waiting();
void loopfun();
void ctrlLoop();
void func();
void factorial();
void saleBook();
void sale3Book();
void prat5_last();
void pract10();
